src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="date")
     */
    private $date_ajout;


    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="produits")
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="produit",cascade={"persist"})
     */
    private $image;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $active;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->image = new ArrayCollection();
        $this->date_ajout=  new \DateTime('now');

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }


    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }


    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImage(): Collection
    {
        return $this->image;
    }

    public function addImage(Image $image): self
    {
        if (!$this->image->contains($image)) {
            $this->image[] = $image;
            $image->setProduit($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->image->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProduit() === $this) {
                $image->setProduit(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getActive(): ?int
    {
        return $this->active;
    }

    public function setActive(int $active): self
    {
        $this->active = $active;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use \App\Form\ImageType;
use App\Entity\Produit;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle')
            ->add('categorie', EntityType::class, [
                'class' => Categorie::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('c')
                        ->orderBy('c.id', 'DESC');
                },
                'choice_label' => 'libelle',

            ])
            ->add('description',TextareaType::class,[
                'required'=>false,
            ])
            ->add('image', CollectionType::class, [
                'entry_type' => ImageType::class,
                'entry_options' => [
                    'label' => false
                ],
                'allow_add' => true,
                'label' => false,
                'by_reference' => false,
                'allow_delete' => true,
                'prototype' => true,

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ImageRepository;
use App\Repository\ProduitRepository;
use App\Services\PaginationService;
use App\Services\UploaderHelper;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;


/**
 * @Route("/admin")
 */
class ProduitController extends AbstractController
{
    /**
     * @Route("/produit", name="produit")
     */
    public function index(PaginationService $paginationService): Response
    {
        $pagination = $paginationService->setEntityClass(Produit::class)->getData();

        return $this->render('_admin/produit/index.html.twig', [
            'pagination' => $pagination,
            'tableau' => [
                'libelle' => 'libelle',
                'date' => 'date',
                'description' => 'description',
            ],

            'modal' => 'modal',
            'titre' => 'Liste des produits',

        ]);
    }

    /**
     * @Route("/produit/{id}/show", name="produit_show", methods={"GET"})
     */
    public function show(Produit $produit): Response
    {
        $form = $this->createForm(produitType::class, $produit, [
            'method' => 'POST',
            'action' => $this->generateUrl('produit_show', [
                'id' => $produit->getId(),
            ])
        ]);

        return $this->render('_admin/produit/voir.html.twig', [
            'produit' => $produit,
            'titre'=>'Produit',
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/produit/new", name="produit_new", methods={"GET","POST"})
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param UploaderHelper $uploaderHelper
     * @param ProduitRepository $repository
     * @return Response
     */
    public function new(Request $request, EntityManagerInterface $em, UploaderHelper $uploaderHelper, ProduitRepository $repository): Response
    {
        $produit = new Produit();

        $form = $this->createForm(ProduitType::class, $produit, [
            'method' => 'POST',
            'action' => $this->generateUrl('produit_new')
        ]);

        $form->handleRequest($request);

        $isAjax = $request->isXmlHttpRequest();

        if ($form->isSubmitted()) {
            $response = [];
            $statut = 1;
            $redirect = $this->generateUrl('produit');

            if ($form->isValid()) {
                $brochureFile = $form->get('image')->getData(); //get('image_prod')->getData();
                // dd($brochureFile);
                foreach ($brochureFile as $image) {
                    $file = new File($image->getPath());
                    $newFilename = md5(uniqid()) . '.' . $file->guessExtension();
                    // $fileName = md5(uniqid()).'.'.$file->guessExtension();
                    $file->move($this->getParameter('images_directory'), $newFilename);
                    $image->setPath($newFilename);
                }
                $produit->setActive(1);
                $em->persist($produit);
                $em->flush();

                $message = 'Opération effectuée avec succès';

                $this->addFlash('success', $message);

            }
            if ($isAjax) {
                return $this->json(compact('statut', 'message', 'redirect'));
            } else {
                if ($statut == 1) {
                    return $this->redirect($redirect);
                }
            }
        }

        return $this->render('_admin/produit/new.html.twig', [
            'produit' => $produit,
            'titre'=>'Produit',
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/produit/{id}/edit", name="produit_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Produit $produit
     * @param EntityManagerInterface $em
     * @param UploaderHelper $uploaderHelper
     * @return Response
     */
    public function edit(Request $request, Produit $produit, EntityManagerInterface $em,UploaderHelper  $uploaderHelper,ImageRepository $imageRepository): Response
    {

        $form = $this->createForm(ProduitType::class, $produit, [
            'method' => 'POST',
            'action' => $this->generateUrl('produit_edit', [
                'id' => $produit->getId(),
            ])
        ]);

        $form->handleRequest($request);

        $isAjax = $request->isXmlHttpRequest();

        $redirect = $this->generateUrl('produit');

        if ($form->isSubmitted() && $form->isValid()) {

                $brochureFile = $form->get('image')->getData();//$_FILES['produit']['tmp_name']['image'];

                 foreach ($brochureFile as $image) {

                     if (str_contains($image->getPath(),'.tmp')){
                         $file = new File($image->getPath());
                         $newFilename = md5(uniqid()) . '.' . $file->guessExtension();
                         // $fileName = md5(uniqid()).'.'.$file->guessExtension();
                         $file->move($this->getParameter('images_directory'), $newFilename);
                         $image->setPath($newFilename);


                     }
                 }


                $em->persist($produit);
                $em->flush();

                $message = 'Opération effectuée avec succès';
                $statut = 1;
                $this->addFlash('success', $message);

          //  }

            if ($isAjax) {
                return $this->json(compact('statut', 'message', 'redirect'));
            } else {
                if ($statut == 1) {
                    return $this->redirect($redirect);
                }
            }
        }

        return $this->render('_admin/produit/edit.html.twig', [
            'form' => $form->createView(),
            'titre'=>'Produit',
        ]);
    }

    /**
     * @Route("/produit/delete/{id}", name="produit_delete", methods={"POST","GET","DELETE"})
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param Produit $produit
     * @return Response
     */
    public function delete(Request $request, EntityManagerInterface $em, Produit $produit): Response
    {


        $form = $this->createFormBuilder()
            ->setAction(
                $this->generateUrl(
                    'produit_delete'
                    , [
                        'id' => $produit->getId()
                    ]
                )
            )
            ->setMethod('DELETE')
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em->remove($produit);
            $em->flush();

            $redirect = $this->generateUrl('produit');

            $message = 'Opération effectuée avec succès';

            $response = [
                'statut' => 1,
                'message' => $message,
                'redirect' => $redirect,
            ];

            $this->addFlash('success', $message);

            if (!$request->isXmlHttpRequest()) {
                return $this->redirect($redirect);
            } else {
                return $this->json($response);
            }


        }
        return $this->render('_admin/produit/delete.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/produit/{id}/active", name="produit_active", methods={"GET"})
     * @param $id
     * @param Produit $parent
     * @param SerializerInterface $serializer
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function active($id, Produit $parent, SerializerInterface $serializer, EntityManagerInterface $entityManager): Response
    {

        if ($parent->getActive() == 1) {

            $parent->setActive(0);

        } else {

            $parent->setActive(1);

        }
        /* $json = $serializer->serialize($parent, 'json', ['groups' => ['normal']]);*/
        $entityManager->persist($parent);
        $entityManager->flush();
        return $this->json([
            'code' => 200,
            'message' => 'ça marche bien',
            'active' => $parent->getActive(),
        ], 200);

    }

    /**
     * @Route("/produit/new1", name="produit_new1", methods={"GET","POST"})
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param UploaderHelper $uploaderHelper
     * @param ProduitRepository $repository
     * @return Response
     */
    public function new1(Request $request, EntityManagerInterface $em, UploaderHelper $uploaderHelper, ProduitRepository $repository): Response
    {
        $produit = new Produit();

        $form = $this->createForm(ProduitType::class, $produit, [
            'method' => 'POST',
            'action' => $this->generateUrl('produit_new')
        ]);

        $form->handleRequest($request);

        $isAjax = $request->isXmlHttpRequest();

        if ($form->isSubmitted()) {
            $response = [];
            $statut = 1;
            $redirect = $this->generateUrl('produit');

            if ($form->isValid()) {

                $brochureFile = $form->get('image')->getData(); //get('image_prod')->getData();
             // dd($brochureFile);
                foreach ($brochureFile as $image) {
                    $file = new File($image->getPath());
                    $newFilename = md5(uniqid()) . '.' . $file->guessExtension();
                    // $fileName = md5(uniqid()).'.'.$file->guessExtension();

templates/_admin/produit/edit.html.twig
{% form_theme form _self %}
{% from '_admin/macros/image.html.twig' import image %}
{% block page_content %}

    <div class="modal-header bg-secondary-gradient">
        <h2 class="modal-title" style="margin-top: -15px;color: white">EDITION-{{ titre | upper  }}</h2>
        <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
    <br>
    {# {% form_theme form 'widget/fields-block.html.twig' %}#}
    {{ form_start(form, {'attr': {'role':'form', 'class': 'form'}}) }}
    <div class="modal-body">

        <div class="contenu" style="margin-top: -10px">

            <div class="row">
                <div class="form-group col-md-6 ">
                    <label class="sr-onl" for="userinput1">LIBELLE</label>
                    {{ form_widget(form.libelle,{'attr':{'class':'form-control border-primary','id':'userinput1','placeholder':'LIBELLE','required':'required' }}) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>
                <div class="form-group col-md-6">
                    <label class="sr-onl" for="userinput1">CATEGORIE</label>
                    {{ form_widget(form.categorie,{'attr':{'class':'form-select  form-control border-primary','id':'userinput1','placeholder':'CATEGORIE' }}) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>

            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="sr-onl" for="userinput1">DESCRIPTION</label>
                    {{ form_widget(form.description,{'attr':{'class':'form-control border-primary','id':'userinput1','placeholder':'DESCRIPTION' }}) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>
            </div>
            <span class="col-lg-12 groupe" id="groupe" data-prototype="{{ image(form.image.vars.prototype)|e('html_attr') }}">

              <h4>LISTE DES IMAGES</h4>
            <div class="col-md-12">
                <a href="#" class="btn btn-secondary add_groupe" style="margin-left: -20px" data-card-tool="remove"
                   data-toggle="tooltip" data-placement="top" title="" data-original-title="Remove Card">Ajouter une
                    image </a>
            </div>
            {% for row in form.image %}
                <span class="container col-md-12">
                    {{ image(row|e) }}

                </span>
            {% endfor %}
 <input class="after" type="hidden"/>
        </span>


        </div>


    </div>
    <div class="modal-footer">
        <a href="{{ path('produit') }}" class="btn btn-secondary">Fermer</a>
        {# <button class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>#}
        <button class="btn btn-primary">Valider</button>
    </div>
    {{ form_end(form) }}


{% endblock %}
{#{% include 'admin/macros/fichier.html.twig'  %}#}

{% block javascripts %}

    <script src="{{ asset('admin/admin/js/jquery3.1.js') }}"></script>
    <script src="{{ asset('admin/admin/js/groupe.js') }}"></script>

    <script>


    </script>
{% endblock %}

templates/_admin/produit/index.html.twig
{% extends '_admin/_includes/index.html.twig' %}

{% block titre %}{{ menu.getRoute }}{% endblock %}

{% block page_content %}

    {% set new = menu.getRoute %}
    {#{{ dump(menu.getRoute) }}#}
    <!-- PAGE-HEADER -->
    <div class="page-header">
        <h1 class="page-title">{{ "Produits" |capitalize }}</h1>
        <div>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path(new) }}">LISTE DES PRODUITS</a></li>{#
                <li class="breadcrumb-item active" aria-current="page">{{ "NOUVEAU CLIENT" | capitalize }}</li>#}
            </ol>
        </div>

    </div>
    <!-- PAGE-HEADER END -->
    <!-- Row -->
    <div class="row row-sm">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-header">
                    <div class="col-md-10">
                        <h3 class="card-title">{{ titre | capitalize }}</h3>
                    </div>
                    <div class="col-md-2">
                        <a class="btn btn-secondary bg-secondary-gradient offset-7" {% if new !="admin" %} href="{{ path(new ~ '_new') }}" {% endif%} {% if modal=="modal" %} data-bs-toggle="modal" data-bs-target="#extralargemodal" {% endif %}>
                            <i class="fe fe-plus"></i>Nouveau
                        </a>
                    </div>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="example2" class="table table-bordered text-nowrap border-bottom">
                            <thead>

                            {% include '_admin/_tableau/header.html.twig' with {'tableau':tableau  }%}

                            </thead>
                            <tbody>
                            {% for data in pagination %}
                                <tr>
                                    <td >
                                        {{ data.libelle | upper }}
                                    </td>
                                    <td >
                                        {{ data.dateAjout | date("m-d-Y") }}
                                    </td>
                                    <td >
                                        {{ data.description | upper }}
                                    </td>

                                    {% include '_admin/_tableau/action.html.twig' with {'module':new ,'data':data }%}

                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


        </div>
    </div>

{% endblock %}

templates/_admin/produit/new.html.twig
{% form_theme form _self %}
{% from '_admin/macros/image.html.twig' import image %}
{% block page_content %}

    <div class="modal-header bg-secondary-gradient">
        <h2 class="modal-title" style="margin-top: -15px;color: white">NOUVEAU-{{ titre | upper  }}</h2>
        <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
    <br>
   {# {% form_theme form 'widget/fields-block.html.twig' %}#}
    {{ form_start(form, {'attr': {'role':'form', 'class': 'form'}}) }}
    <div class="modal-body">

        <div class="contenu" style="margin-top: -10px">

            <div class="row">
                <div class="form-group col-md-6 ">
                    <label class="sr-onl" for="userinput1">LIBELLE</label>
                    {{ form_widget(form.libelle,{'attr':{'class':'form-control border-primary','id':'userinput1','placeholder':'LIBELLE','required':'required' }}) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>
                <div class="form-group col-md-6">
                    <label class="sr-onl" for="userinput1">CATEGORIE</label>
                    {{ form_widget(form.categorie,{'attr':{'class':'form-select  form-control border-primary','id':'userinput1','placeholder':'CATEGORIE' }}) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>

            </div>
             <div class="row">
                 <div class="form-group col-md-12">
                     <label class="sr-onl" for="userinput1">DESCRIPTION</label>
                     {{ form_widget(form.description,{'attr':{'class':'form-control border-primary','id':'userinput1','placeholder':'DESCRIPTION' }}) }}
                     {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                 </div>
             </div>
            <span class="col-lg-12 groupe" id="groupe" data-prototype="{{ image(form.image.vars.prototype)|e('html_attr') }}">

              <h4>LISTE DES IMAGES</h4>
            <div class="col-md-12">
                <a href="#" class="btn btn-secondary add_groupe" style="margin-left: -20px" data-card-tool="remove"
                   data-toggle="tooltip" data-placement="top" title="" data-original-title="Remove Card">Ajouter une
                    image </a>
            </div>
            {% for row in form.image %}
                <span class="container col-md-12">
                    {{ image(row|e) }}

                </span>
            {% endfor %}
 <input class="after" type="hidden"/>
        </span>


        </div>


    </div>
    <div class="modal-footer">
        <a href="{{ path('produit') }}" class="btn btn-secondary">Fermer</a>
       {# <button class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>#}
        <button class="btn btn-primary">Valider</button>
    </div>
    {{ form_end(form) }}


{% endblock %}
{#{% include 'admin/macros/fichier.html.twig'  %}#}

{% block javascripts %}

    <script src="{{ asset('admin/admin/js/jquery3.1.js') }}"></script>
    <script src="{{ asset('admin/admin/js/groupe.js') }}"></script>

    <script>


    </script>
{% endblock %}

templates/_admin/produit/voir.html.twig
{% form_theme form _self %}
{% from '_admin/macros/image.html.twig' import image %}
{% block page_content %}

    <div class="modal-header bg-secondary-gradient">
        <h2 class="modal-title" style="margin-top: -15px;color: white">détails-{{ titre | upper  }}</h2>
        <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
    <br>
    {# {% form_theme form 'widget/fields-block.html.twig' %}#}
    {{ form_start(form, {'attr': {'role':'form', 'class': 'form'}}) }}
    <div class="modal-body">

        <div class="contenu" style="margin-top: -10px">

            <div class="row">
                <div class="form-group col-md-6 ">
                    <label class="sr-onl" for="userinput1">LIBELLE</label>
                    {{ form_widget(form.libelle,{'attr':{'class':'form-control border-primary','id':'userinput1','placeholder':'LIBELLE','required':'required' }}) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>
                <div class="form-group col-md-6">
                    <label class="sr-onl" for="userinput1">CATEGORIE</label>
                    {{ form_widget(form.categorie,{'attr':{'class':'form-select  form-control border-primary','id':'userinput1','placeholder':'CATEGORIE' }}) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>

            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="sr-onl" for="userinput1">DESCRIPTION</label>
                    {{ form_widget(form.description,{'attr':{'class':'form-control border-primary','id':'userinput1','placeholder':'DESCRIPTION' }}) }}
                    {# <input type="text" id="userinput1" class="form-control border-primary" placeholder="Compte contribuable" name="name">#}
                </div>
            </div>
            <span class="col-lg-12 groupe" id="groupe" data-prototype="{{ image(form.image.vars.prototype)|e('html_attr') }}">

              <h4>LISTE DES IMAGES</h4>
            <div class="col-md-12">
                <a href="#" class="btn btn-secondary add_groupe" style="margin-left: -20px" data-card-tool="remove"
                   data-toggle="tooltip" data-placement="top" title="" data-original-title="Remove Card">Ajouter une
                    image </a>
            </div>
            {% for row in form.image %}
                <span class="container col-md-12">
                    {{ image(row|e) }}

                </span>
            {% endfor %}
 <input class="after" type="hidden"/>
        </span>


        </div>


    </div>
    <div class="modal-footer">
        <a href="{{ path('produit') }}" class="btn btn-secondary">Fermer</a>
    </div>
    {{ form_end(form) }}


{% endblock %}
{#{% include 'admin/macros/fichier.html.twig'  %}#}

{% block javascripts %}

    <script src="{{ asset('admin/admin/js/jquery3.1.js') }}"></script>
    <script src="{{ asset('admin/admin/js/groupe.js') }}"></script>

    <script>


    </script>
{% endblock %}